name: TI_Radar_GUI
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyserial
  - matplotlib
  - scipy
  - numpy
  - pyqt
  - imageio
  - jupyterlab
  - pandas
  - ipykernel
  - spyder
  - scikit-learn
  - tqdm
  - natsort
  - pip
  - pip:
    - open3d
    - imageio[ffmpeg]
