name: TI_Radar_GUI
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyserial
  - matplotlib
  - scipy
  - numpy
  - imageio[ffmpeg]
  - jupyterlab
  - pandas
  - ipykernel
  - spyder
  - scikit-learn
  - tqdm
  - natsort
  - open3d
  - opencv-python
